baseURL = "https://crit.vulnetix.com/"
[languages.en]
  languageName = "English"
  weight = 1
  locale = "en-GB"

title = "CRIT — Cloud Resource Identifier Templates"

enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
  style = "monokai"
  lineNos = false

[params]
  description = "Cloud Resource Identifier Templates — a machine-readable format for identifying cloud resources affected by known vulnerabilities."
  tagline = "CVSS-style for cloud-native CVEs."
  githubURL = "https://github.com/Vulnetix/ietf-crit-spec"
  ietfDraftURL = "https://datatracker.ietf.org/doc/draft-vulnetix-crit/"
  ogImage = "/assets/vulnetix-og-square.png"
